# Generated by Django 3.1.7 on 2021-08-05 08:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_akun', models.CharField(choices=[('pegawai', 'Pegawai'), ('operatoropd', 'OperatorOpd'), ('operator', 'Operator'), ('admin', 'Administrator')], max_length=20)),
                ('akun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BerkalaHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('kgb_nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('kgb_tanggal', models.DateTimeField(auto_now=True, null=True)),
                ('tmt', models.DateField(blank=True, null=True)),
                ('tmt_baru', models.DateField(blank=True, null=True)),
                ('golongan', models.CharField(max_length=5)),
                ('pejabat_ttd', models.CharField(default='GUBERNUR JAMBI', max_length=255)),
                ('mk_lama_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_lama_bulan', models.IntegerField(blank=True, null=True)),
                ('kgb_image', models.FileField(blank=True, null=True, upload_to='media')),
                ('mk_baru_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_baru_bulan', models.IntegerField(blank=True, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='upload/skberkala/')),
            ],
        ),
        migrations.CreateModel(
            name='GajiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_kerja', models.IntegerField()),
                ('tbgaji_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('terbilang', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GolonganModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nilai', models.IntegerField()),
                ('simbol', models.CharField(max_length=10, null=True)),
                ('grade', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='JabatanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(blank=True, default='jfu', max_length=20, null=True)),
                ('nama', models.CharField(default='', max_length=150)),
                ('bup', models.IntegerField()),
                ('jenjang', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OpdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kepala_opd', models.IntegerField(blank=True, default=0, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('telpon', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.akunmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=100, null=True)),
                ('pengguna', models.IntegerField(blank=True, null=True)),
                ('alamat', models.CharField(max_length=255)),
                ('telpon', models.CharField(max_length=30)),
                ('gaji_skrg', models.IntegerField(blank=True, default=0, null=True)),
                ('tmt_cpns', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fhoto', models.ImageField(upload_to='upload/fhoto/')),
                ('nominasi', models.BooleanField(default=False)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=30, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('jabatan_data', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('pddk_terakhir', models.CharField(blank=True, max_length=100, null=True)),
                ('tmt_pns', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('tgllahir', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(default='7', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProsesBerkalaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('selesai', 'Selesai'), ('tertunda', 'Tertunda'), ('proses', 'Proses'), ('nominatif', 'Nominatif')], default='nominatif', max_length=20)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel')),
            ],
        ),
        migrations.CreateModel(
            name='NominatifxModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True)),
                ('bahan', models.CharField(blank=True, choices=[('l', 'Lengkap'), ('tl', 'Tidak Lengkap')], max_length=20)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel')),
            ],
        ),
        migrations.CreateModel(
            name='NominatifTundaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True, verbose_name='TMT KGB')),
                ('keterangan', models.CharField(blank=True, max_length=20, null=True)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel', verbose_name='Unit Kerja')),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel', verbose_name='Nama')),
            ],
        ),
        migrations.CreateModel(
            name='NominatifSelesaiModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_tahun', models.IntegerField(blank=True, null=True)),
                ('mk_bulan', models.IntegerField(blank=True, null=True)),
                ('mkb_tahun', models.IntegerField(blank=True, null=True)),
                ('mkb_bulan', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('tmt_kgb', models.DateField(blank=True, null=True)),
                ('gaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('golongan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
                ('jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.jabatanmodel')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
                ('pegawai', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.pegawaimodel')),
            ],
        ),
        migrations.CreateModel(
            name='GolonganHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.IntegerField(blank=True, null=True)),
                ('nip', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP')),
                ('nomor_sk', models.CharField(blank=True, default='S-10225/BKD-2.2/', max_length=150, null=True)),
                ('jenis', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal', models.DateField(blank=True, default=1998, null=True)),
                ('dokumen', models.FileField(blank=True, null=True, upload_to='upload/berkas/')),
                ('mk_tahun', models.IntegerField(default=0, null=True)),
                ('mk_bulan', models.IntegerField(default=0, null=True)),
                ('dasarnominatif', models.BooleanField(default=False, null=True)),
                ('tglpenetapan', models.DateField(blank=True, null=True)),
                ('pejabat', models.CharField(blank=True, default='GUBERNUR JAMBI', max_length=50, null=True)),
                ('nama', models.ForeignKey(blank=True, default=24, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel')),
            ],
            options={
                'managed': (True,),
            },
        ),
        migrations.AddField(
            model_name='gajimodel',
            name='golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.golonganmodel'),
        ),
        migrations.AddField(
            model_name='akunmodel',
            name='opd_akses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel'),
        ),
    ]
