# Generated by Django 3.1.7 on 2021-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210809_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golonganhistorymodel',
            old_name='dokumen',
            new_name='gambar',
        ),
        migrations.AddField(
            model_name='nominatifselesaimodels',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrbarcode/'),
        ),
    ]
